Algoritmo "consumo"

Var
// Seção de Declarações das variáveis

   distanciaPercorrida: inteiro
   combustivelGasto, consumoMedio: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("digite a distancia percorrida:")
   leia(distanciaPercorrida)
   escreva("digite o valor do comnudtivel gasto:")
   leia(combustivelGasto)


   consumoMedio <- distancia / combustivel
   escreval("O consumo médio é de: ", consumoMedio:8:3)

Fimalgoritmo